HW2 is partly completed
avoronov/otus_golang_hw pull request #2
Opened 2020-09-09 12:49 UTC by avoronov

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-09-09 17:07 UTC, kulti requested changes
Думаю, что проверка isLetter не нужна. В задании говорится о символах, а этом могут быть и знаки пунктуации и прочее. На умляуту предлагаю забить.

Видимо, из-за этой проверки решение переусложнилось. Предлагаю упростить.

2020-09-09 17:07 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	if unicode.IsLetter(curr) {
Не уверен, что это нужно. Например, размножать пробелы вполне себе рабочий юз-кейс.

2020-09-09 17:07 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		_, err = doStep(0, prev, &result)
Сомнительное решение:
1. Передается магический 0.
2. Внутри doStep тоже есть проверка prev на 0.

Если все упростить, то вместо вызова большой функции doStep получится просто `result.WriteRune(prev)`.

2020-09-11 19:01 UTC, kulti approved these changes, later dismissed
Теперь ничего лишнего. ДЗ принято - 10/10.

2020-09-14 17:19 UTC, kulti requested changes
Явно что-то напутано в логике эскейпинга. Либо я совсем не понял идею. Например, простейшие кейзы "\" и "\4" не работают, как ожидается (должны быть ошибка и 4, соответственно).

2020-09-14 17:19 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			if !escape {
Тут что-то у меня логика не сходится. escape будет в том случае, если prev == "\\", но при этом уже есть проверка IsDigit(prev). Есть тест-кейз на этот случай?

2020-09-14 17:19 UTC, kulti commented on hw02_unpack_string/unpack.go
> +				continue
escape, наверно, нужно сбросить, раз его свойство уже применили?

2020-09-14 17:19 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		}
Здесь, наверно, нужно наоборот. Если уже escape и встретили '\\', то надо записать руну, а если еще не escape, то выставить флаг и continue.

2020-09-15 10:04 UTC, avoronov commented
> Явно что-то напутано в логике эскейпинга. Либо я совсем не понял идею. Например, простейшие кейзы "" и "\4" не работают, как ожидается (должны быть ошибка и 4, соответственно).

В кейсе с "" ошибки быть не должно, судя по изначальному описанию задачи и прилагающимся тестам (https://github.com/OtusGolang/home_work/blob/master/hw02_unpack_string/unpack_test.go#L41).

2020-09-15 10:13 UTC, avoronov commented on hw02_unpack_string/unpack.go
> +			if !escape {
> escape будет в том случае, если prev == "\", 
не совсем так - escape == true значит что '\' встретилась на предыдущем шаге или два шага назад. В подобном случае (\ встретилась два шага назад) подобная проверка имеет смысл.

2020-09-15 10:16 UTC, avoronov commented on hw02_unpack_string/unpack.go
> +				continue
Если escape сбросиnm, то тогда мы не сможем различать случаи '45' и '\45'. На шаге с цифрой 5 мы не сможем сказать, была ли заэскейплена цифра 4 на предудыщем шаге и все ок или же мы имеем ситуацию с двумя цифрами подряд, что по условиям задачи является ошибкой.

2020-09-15 10:22 UTC, avoronov commented on hw02_unpack_string/unpack.go
> +		}
При моем подходе все так и произойдет, за искуллючением того что руна будет записана на следующем шаге.

2020-09-15 11:14 UTC, kulti commented
> > Явно что-то напутано в логике эскейпинга. Либо я совсем не понял идею. Например, простейшие кейзы "" и "\4" не работают, как ожидается (должны быть ошибка и 4, соответственно).
> 
> В кейсе с "" ошибки быть не должно, судя по изначальному описанию задачи и прилагающимся тестам (https://github.com/OtusGolang/home_work/blob/master/hw02_unpack_string/unpack_test.go#L41).

Маркдаун съел слэш. Подправил изначальный комментарий. Там речь про "\\".

2020-09-15 11:17 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			if !escape {
> escape == true значит что ''встретилась на предыдущем шаге или два шага назад".

Это объясняет, почему я не понял логику этого решения. До этого невозможно догадаться, читая код :)

2020-09-15 11:18 UTC, kulti commented on hw02_unpack_string/unpack.go
> +				continue
Можно на это посмотреть так: если 4 заэскейпили, то она становится простым символом (prev = curr), который 5 размножит на следующем шаге.

2020-09-15 11:19 UTC, kulti commented on hw02_unpack_string/unpack.go
> +		}
Почему на следующем? Запись произойдет уже на этом шаге, т.к. сразу после if'a `result.WriteRune(prev)`. Именно поэтому и не работают случаи "\\" и "\\4".

2020-09-15 11:21 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			if !escape {
Предлагаю оставить флагу escape простое и понятное значение "текущий символ нужно заэскейпить". Тогда все станет проще и понятнее. Про случай "\\45" отписал в соответствующем дискашене.

2020-09-15 16:36 UTC, avoronov commented on hw02_unpack_string/unpack.go
> +		}
Эти случаи не работают все же из-за другого, я пофиксил и сейчас код обрабатывает такие случаи правильно. Но код получился, возможно, не самый понятный - попробую его переделать.

2020-09-15 16:48 UTC, avoronov commented on hw02_unpack_string/unpack.go
> +				continue
Как это поможет различать случаи "45" и "\45"? На шаге, когда curr == 5, мы должны каким-то образом различать два эти случая (при подходе "если 4 заэскейпили, то она становится простым символом (prev = curr)" пока не соображу как это можно сделать).

2020-09-15 16:53 UTC, avoronov commented on hw02_unpack_string/unpack.go
> +		}
Еще отмечу, что в случае "Если уже escape и встретили '\' " запись руны сразу повлечет за собой необходимость добавить логику, которая будет корректно вычислять, сколько раз  необходимо повторить руну для строк, подобных "\\5", когда руну при парсинге 5 нужно будет повторить не 5, а 4 раза (с учетом уже записанной руны)

2020-09-15 17:10 UTC, kulti commented on hw02_unpack_string/unpack.go
> +				continue
Я понял, в чем проблема. Дело в проверке `if prev == 0` -> `prev = curr`. Это немного ломает стройность основного тела цикла.

Предлагаю убрать эту проверку. Тогда, логика станет проще и не нужно будет запоминать пред-предыдущий символ. Подумайте над флоу, которые я описал ниже

Для случая "a5" была бы такая логика:
1. curr = a. Ничего интересного, запомнили a (prev = a).
2. curr = 5. Есть предыдущий символ (a)  — размножаем его 5 раз.

Для случая "\\45" логика была бы такая :
1. curr = \\. Включаем режим эскейпинга (escape = true).
2. curr = 4. Включен эскейпинг. Выключаем эскейпинг и prev = 4.
3. curr = 5. Есть предыдущий символ (4) — размножаем его 5 раз.

Для случая "45" логика была бы такая :
1. curr = 4. Предыдущего символа нет — ошибка.

2020-09-16 13:54 UTC, avoronov commented on hw02_unpack_string/unpack.go
> +				continue
Переработал сове решение, тесты проходят :)

2020-09-17 16:29 UTC, kulti submitted a review, later dismissed
Теперь и решение со звездочкой стало понятным 👍

2020-09-17 16:29 UTC, kulti commented on hw02_unpack_string/unpack.go
> +	if escape && prev == 0 {
Проверка на prev == 0 немного сбивает с толку. По идее, если после цикла осталось состояние escape, то это уже ошибка.

Все работает, т.к. prev сбрасывается в 0, когда включается escape режим.

2020-09-18 19:47 UTC, kulti approved these changes

2020-09-18 19:49 UTC, merged