Hw07 file copying
avoronov/otus_golang_hw pull request #8
Opened 2020-11-09 21:56 UTC by avoronov

## Домашнее задание №7 «Утилита для копирования файлов»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-11-15 16:51 UTC, Antonboom requested changes
Здравствуйте!

Согласно критериям оценки не хватает юнит-тестов.

Предварительно
5 / 10

2020-11-15 16:51 UTC, Antonboom commented on hw07_file_copying/copy_test.go
> +	// err := Copy("testdata/input.txt", "out.txt", 10000, 100)
а где тесты?

2020-11-15 16:51 UTC, Antonboom commented on hw07_file_copying/main.go
> +		fmt.Print(err)
возвращать ненулевой код возврата (os.Exit(1) / log.Fatal)

2020-11-15 16:51 UTC, Antonboom commented on hw07_file_copying/copy.go
> +	bar.Finish()
defer?

2020-11-15 16:51 UTC, Antonboom commented on hw07_file_copying/copy.go
> +	bar := pb.Start64(limit)
чем `NewProxyReader` не подошёл?

2020-11-15 16:51 UTC, Antonboom commented on hw07_file_copying/copy.go
> +func prepareSourceAndLimit(fromPath string, offset, limit int64) (*os.File, int64, error) {
не слишком сильное дробление на функции?

2020-11-16 19:48 UTC, avoronov commented on hw07_file_copying/copy_test.go
> +	// err := Copy("testdata/input.txt", "out.txt", 10000, 100)
Раскомментить забыл (

2020-11-16 19:58 UTC, avoronov commented on hw07_file_copying/copy.go
> +	bar := pb.Start64(limit)
Там буфер такого размера выделяется, что весь тестовый файл за один заход копируется и не виднр красивой анимации, поэтому решил в рукопашную сделать

2020-11-17 04:39 UTC, Antonboom approved these changes
Принято
8 / 10

2020-11-17 04:39 UTC, Antonboom commented on hw07_file_copying/copy_test.go
>  	Copy("testdata/input.txt", "out.txt", 0, 10)
не хватает ассерта на то, что же лежит в out.txt?

2020-12-16 22:34 UTC, merged